[[streams]]
label = "Nova Kakhovka: st. Druzhba & Mayakovsky"
link = "https://www.youtube.com/watch?v=VpUaEvy_-iM"

[[streams]]
label = "Kyiv #1"
link = "https://www.youtube.com/watch?v=5_aQWobOop8"

[[streams]]
label = "Kyiv #2"
link = "https://www.youtube.com/watch?v=AKsvwfmY99w"

[[streams]]
label = "Kyiv #3"
link = "https://www.youtube.com/watch?v=2vBiebeMD6Y"

[[streams]]
label = "Hotel Kyiv Rus, Lviv Oblast Ukraine (WC)"
link = "https://www.youtube.com/watch?v=tebpAZk95UI"

[[streams]]
label = "Kakhovka"
link = "https://www.youtube.com/v/3Iq8h4W4HJY"

[[streams]]
label = "Nova Kakhovka, view of the Dnieper river"
link = "https://www.youtube.com/watch?v=b2qv0V7kQUs"

[[streams]]
label = "Nova Kakhovka, the intersection of st. French and Factory"
link = "https://www.youtube.com/watch?v=sUnx7HoA1LM"

[[streams]]
label = "Kyiv - Multicam"
link = "https://www.youtube.com/watch?v=iZebYm-nenY"

[[streams]]
label = "Nova Kakhovka, view of Victory Avenue from the plant 'Falcon'"
link = "https://www.youtube.com/watch?v=jl13AuPIoJ4"

[[streams]]
label = "Kakhovka - Dnieper River towards Kherson"
link = "https://www.youtube.com/watch?v=3BxMw8vRJTE"

[[streams]]
label = "Multicam"
link = "https://www.youtube.com/watch?v=HIPNVm6lNfM"


[[streams]]
label = "Victory Square"
link = "https://www.youtube.com/watch?v=VNCKH430Xfg"
    
[[streams]]
label = "Koblevo Beach (WC)"
link = "https://www.youtube.com/watch?v=ZS4tYIumdcc"

[[streams]]
label = "Feodosia Crimean Peninsula (WC)"
link = "https://www.youtube.com/watch?v=p0nwFg20CvU"